name: Keep Twilio Sandbox Alive

on:
  schedule:
    - cron: '0 5 * * *'  # 05:00 UTC = 08:00 Israel time
  workflow_dispatch:

jobs:
  ping-twilio-sandbox:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Twilio SDK
        run: pip install twilio

      - name: Send WhatsApp ping to keep sandbox alive
        env:
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_FROM: ${{ secrets.TWILIO_FROM }}
          TWILIO_TO: ${{ secrets.TWILIO_TO }}
        run: python send_twilio_ping.py
