name: Keep Twilio Sandbox Alive

on:
  schedule:
    - cron: '0 5 * * *'  # 05:00 UTC = 08:00 Israel time
  workflow_dispatch:

jobs:
  ping-twilio-sandbox:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Twilio SDK
        run: pip install twilio

      - name: Send WhatsApp ping to keep sandbox alive
        env:
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_FROM: ${{ secrets.TWILIO_FROM }}
          TWILIO_TO: ${{ secrets.TWILIO_TO }}
        run: |
          python -c "
import os
from twilio.rest import Client

sid = os.getenv('TWILIO_SID')
token = os.getenv('TWILIO_AUTH_TOKEN')
from_whatsapp = os.getenv('TWILIO_FROM')
to_whatsapp = os.getenv('TWILIO_TO')

client = Client(sid, token)
try:
    msg = client.messages.create(
        body='📢 Daily ping: keep Twilio sandbox alive',
        from_=from_whatsapp,
        to=to_whatsapp
    )
    print(f'[Twilio] Sent message SID: {msg.sid}')
except Exception as e:
    print(f'[Twilio] Failed to send message: {e}')
"
